services:
  memeapi:
    build: .
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BlobStorage_Access_Key=Development
      - BlobStorage_Access_Key_Secret=Development
      - BlobStorage_ServiceUrl=Development
      - DATABASE_CONNECTION_STRING=Host=postgres;Database=memeapi;Username=postgres;Password=yourpassword
    depends_on:
      - postgres
    volumes:
      - ./:/data

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=memeapi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres_data:
